name: EventCore
version: '${version}'
main: lol.aabss.eventcore.EventCore
api-version: '1.13'
authors:
  - aabss
description: Hosting events has never been easier!
website: https://aabss.lol
softdepend:
  - PlaceholderAPI
  - Skript

commands:
  eventcore:
    aliases: [event]
    description: Main command for EventCore
  revive:
    description: Revive a player.
  reviveall:
    description: Revive all players.
  tpalive:
    aliases: [teleportalive]
    description: Teleports all alive players to you.
  tpdead:
    aliases: [teleportdead]
    description: Teleports all dead players to you.
  alivelist:
    description: Lists all alive people.
  visibility:
    aliases: [hide]
    description: Hides players from you.
  deadlist:
    description: Lists all dead people.
  userevive:
    aliases: [viewrevive]
    description: Uses a revive.
  balrevive:
    aliases: [revivebal, revivebalance]
    description: Checks a player's balance.
  giverevive:
    aliases: [addrevive]
    description: Adds revives to a specified player's balance.
  setrevive:
    description: Sets a player's revive amount.
  takerevive:
    aliases: [removerevive]
    description: Removes revives to a specified player's balance.
  killalive:
    description: Kills all alive players.
  killdead:
    description: Kills all dead players.
  clearalive:
    description: Clears the inventory of all alive players.
  cleardead:
    description: Clears the inventory of all dead players.
  givealive:
    description: Gives all alive players items.
  givedead:
    description: Gives all dead players items.
  unrevive:
    description: Unrevives a player.
  healdead:
    description: Heals all dead players.
  healalive:
    description: Heals all alive players.
  mutechat:
    description: Mutes/unmutes the chat.
  recentrev:
    aliases: [revrecent, reviverecent, recentrevive]
    description: Mutes/unmutes the chat.
