name: EventCore
version: '${version}'
main: lol.aabss.eventcore.EventCore
api-version: '1.13'
authors: [aabss]
description: Hosting events has never been easier!
website: https://aabss.lol
softdepend: [PlaceholderAPI]

commands:
  eventcore:
    aliases: [event, events]
    description: Main command for EventCore
  revive:
    description: Revive a player
  reviveall:
    description: Revive all players
  tpalive:
    description: Teleports all alive players to you.
    aliases: teleportalive
  tpdead:
    description: Teleports all dead players to you.
    aliases: teleportdead
  alivelist:
    description: Lists all alive people.
  visibility:
    description: Hides players from you.
    aliases: [hide]
  deadlist:
    description: Lists all dead people.
  userevive:
    aliases:
      - viewrevive
    description: Uses a revive.
  balrevive:
    aliases:
      - revivebal
      - revivebalance
    description: Checks a player's balance.
  giverevive:
    aliases:
      - addrevive
    description: Adds revives to a specified player's balance.
  setrevive:
    description: Sets a player's revive amount.
  takerevive:
    aliases:
      - removerevive
    description: Removes revives to a specified player's balance.

