name: EventCore
version: '${version}'
main: cc.aabss.eventcore.EventCore
api-version: '1.13'
authors:
  - aabss
contributors: [xCheezie]
description: Hosting events has never been easier!
website: https://aabss.cc
softdepend:
  - PlaceholderAPI
  - Skript
