name: EventCore
version: '${version}'
main: app.qwertz.eventcore.EventCore
api-version: '1.13'
authors: [aabss, QWERTZ_EXE]
contributors: [xCheezie]
description: Hosting events has never been easier!
website: https://qwertz.app
softdepend: [PlaceholderAPI, Skript]